// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWoKjTH0o4z0CXYMKnKLSIinZuY5vMNpk',
    appId: '1:932345541125:web:af516b8a1e9fcacaaf226c',
    messagingSenderId: '932345541125',
    projectId: 'ahamuch-df380',
    authDomain: 'ahamuch-df380.firebaseapp.com',
    storageBucket: 'ahamuch-df380.appspot.com',
    measurementId: 'G-071ZKFBGGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnDBWzRNgxCK-SNwZg4REL3PII8jEYQPA',
    appId: '1:932345541125:android:75628d790708a01caf226c',
    messagingSenderId: '932345541125',
    projectId: 'ahamuch-df380',
    storageBucket: 'ahamuch-df380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA97ELNRmob7gFwGOLen4eFivYfByBPnQk',
    appId: '1:932345541125:ios:2106d502ad333f24af226c',
    messagingSenderId: '932345541125',
    projectId: 'ahamuch-df380',
    storageBucket: 'ahamuch-df380.appspot.com',
    iosClientId: '932345541125-bo63pq7d5pdug2cfbse925a70al0ar0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahamatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA97ELNRmob7gFwGOLen4eFivYfByBPnQk',
    appId: '1:932345541125:ios:2106d502ad333f24af226c',
    messagingSenderId: '932345541125',
    projectId: 'ahamuch-df380',
    storageBucket: 'ahamuch-df380.appspot.com',
    iosClientId: '932345541125-bo63pq7d5pdug2cfbse925a70al0ar0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahamatch',
  );
}
